Models/ArbitraryLdapSearchForm.cs
namespace HushWeb.Models;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using HushWeb.Validators;

/// <summary>
/// Form used by an administrator to perform an arbitrary ldapsearch.
/// </summary>
public class ArbitraryLdapSearchForm
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ArbitraryLdapSearchForm"/> class.
    /// </summary>
    public ArbitraryLdapSearchForm() { }

    /// <summary>
    /// LDAP bind DN.
    /// </summary>
    [Display(Name = "Bind DN")]
    [Required]
    public string BindDN { get; set; } = null!;

    /// <summary>
    /// Search base for ldapsearch.
    /// </summary>
    [Display(Name = "Search Base")]
    [Required]
    public string SearchBase { get; set; } = null!;

    /// <summary>
    /// Search scope for ldapsearch.
    /// </summary>
    [Display(Name = "Scope")]
    [Required]
    public string Scope { get; set; } = null!;

    /// <summary>
    /// Search filter for ldapsearch.
    /// </summary>
    [Display(Name = "Filter")]
    public string Filter { get; set; } = null!;

    /// <summary>
    /// LDAP bind password.
    /// </summary>
    [Display(Name = "Password")]
    [Required]
    public string Password { get; set; } = null!;
}

Controllers/AdminController.cs
namespace HushWeb.Controllers;

using Microsoft.AspNetCore.Mvc;
using HushWeb.Models;
using HushWeb.Services.LdapUtils;
using HushWeb.Services.CryptoPermissions;
using Newtonsoft.Json;
using HushWeb.Services.ApplicationStore;
using HushWeb.Services.PgpKeystore;

/// <summary>
/// Controller for administrative actions. While it is publically accessible,
/// performing any real changes requires administrative permission.
/// </summary>
public class AdminController : Controller
{
    private readonly LdapUtilsService ldap;
    private readonly CryptoPermissionsService cryptoPermissions;
    private readonly ApplicationStoreService applicationStore;
    private readonly PgpKeystoreService pgpKeystore;

    /// <summary>
    /// Initializes a new instance of the <see cref="AdminController"/> class.
    /// </summary>
    /// <param name="ldap">
    /// Service used to interact with LDAP server.
    /// </param>
    /// <param name="cryptoPermissions">
    /// Service used to interact with permission blocks.
    /// </param>
    /// <param name="applicationStore">
    /// Service used to interact with application store.
    /// </param>
    /// <param name="pgpKeystore">
    /// Service used to interact with PGP public keystore.
    /// </param>
    public AdminController(
        LdapUtilsService ldap,
        CryptoPermissionsService cryptoPermissions,
        ApplicationStoreService applicationStore,
        PgpKeystoreService pgpKeystore
    )
    {
        this.cryptoPermissions = cryptoPermissions;
        this.ldap = ldap;
        this.applicationStore = applicationStore;
        this.pgpKeystore = pgpKeystore;
    }

    /// <summary>
    /// Admin homepage. Contains a list of links to administrative tools.
    /// </summary>
    public IActionResult Index()
    {
        return View();
    }

    /// <summary>
    /// View containg a form to submit a permission block to be decrypted and
    /// decoded.
    /// </summary>
    public IActionResult DecodePermissionBlock() => View();

    /// <summary>
    /// Handles submission of permission block messages to be decoded.
    /// </summary>
    /// <param name="message">
    /// Permission block message to be decoded.
    /// </param>
    /// <returns>
    /// JSON encoding of permission block content.
    /// </returns>
    public IActionResult SubmitDecodePermissionBlock([FromForm] string message)
    {
        var json = cryptoPermissions.DecryptPermissionBlock(message);
        var obj = JsonConvert.DeserializeObject(json);
        var indented = JsonConvert.SerializeObject(obj, Formatting.Indented);
        return Content(indented);
    }

    /// <summary>
    /// Looks up a view containing a form to create a permission block of the
    /// specified type.
    /// </summary>
    /// <param name="id">
    /// Name of the view to lookup.
    /// </param>
    /// <returns>
    /// View containing a permission block form.
    /// </returns>
    public IActionResult EncodePermissionBlock([FromRoute] string id)
    {
        if (!PermissionType.AllTypes.Contains(id))
        {
            return Content("Permission type was not found.");
        }

        return View($"Views/Admin/EncodePermissionBlock/{id}.cshtml");
    }

    /// <summary>
    /// Contains <see cref="ArbitraryLdapSearchForm"/>.
    /// </summary>
    public IActionResult ArbitraryLdapSearch() => View();

    /// <summary>
    /// Handles submission of the <see cref="ArbitraryLdapSearchForm"/>.
    /// Executes an arbitrary ldapsearch.
    /// </summary>
    /// <param name="model">
    /// Form to validate and process.
    /// </param>
    /// <returns>
    /// LDIF results from the ldapsearch.
    /// </returns>
    public async Task<IActionResult> SubmitArbitraryLdapSearch(
        [FromForm] ArbitraryLdapSearchForm model
    )
    {
        if (!ModelState.IsValid)
        {
            return Content($"Validation errors:{ModelState.ToBulletList()}");
        }

        // TODO: Get these strings from the Admin static class
        if (
            model.BindDN != "cn=admin,dc=hush,dc=rip"
            && model.BindDN != "cn=config,dc=hush,dc=rip"
        )
        {
            return Content("Invalid Bind DN");
        }

        var result = await ldap.SearchRaw(
            model.BindDN,
            model.SearchBase,
            model.Password,
            model.Scope,
            model.Filter
        );
        return Content(
            result.ExitCode == 0 ? "LDAP search failed." : result.Output
        );
    }

    /// <summary>
    /// Used to submit a <see cref="DeleteAccountPermissionBlock"/>.
    /// </summary>
    public IActionResult DeleteAccount() => View();

    /// <summary>
    /// Validates the permission block and deletes a user account.
    /// </summary>
    public async Task<IActionResult> SubmitDeleteAccount(
        [FromForm] ArbitraryPermissionBlockForm model
    )
    {
        if (!ModelState.IsValid)
        {
            var notice =
                "Account deletion failed due to the following validation errors:";
            notice += ModelState.ToBulletList();
            return Content(notice);
        }

        DeleteAccountPermissionBlock? permissionBlock = null;

        try
        {
            var json = cryptoPermissions.DecryptPermissionBlock(
                model.PermissionBlock
            );
            permissionBlock =
                JsonConvert.DeserializeObject<DeleteAccountPermissionBlock>(
                    json
                );
        }
        catch { }

        if (permissionBlock == null)
        {
            return Content("Failed to decode permission block.");
        }

        if (!permissionBlock.IsValid())
        {
            return Content("error", "Invalid permission block.");
        }

        var deleted = await LdapHelper.DeleteUser(
            ldap,
            permissionBlock.UniqueId!
        );

        if (!deleted)
        {
            return Content(
                $"Failed to delete user account: {permissionBlock.UniqueId}"
            );
        }

        return Content($"Deleted user account: {permissionBlock.UniqueId}");
    }

    /// <summary>
    /// Allows admin to view applications.
    /// </summary>
    /// <param name="noticeType">
    /// Notice type for form result.
    /// </param>
    /// <param name="noticeText">
    /// Notice text for form result.
    /// </param>
    /// <param name="uniqueId">
    /// Applicant unique ID.
    /// </param>
    public async Task<IActionResult> ViewApplication(
        string? noticeType,
        string? noticeText,
        [FromForm] string? uniqueId
    )
    {
        if (noticeType != null && noticeText != null)
        {
            ViewBag.NoticeType = noticeType;
            ViewBag.NoticeText = noticeText;
        }

        if (!string.IsNullOrWhiteSpace(uniqueId))
        {
            ViewBag.uniqueId = uniqueId;
            ViewBag.permissionBlock = await applicationStore.GetApplication(
                uniqueId
            );
        }

        ViewBag.applicantUniqueIds =
            await applicationStore.GetAllApplicantUniqueIds();

        return View();
    }

    /// <summary>
    /// Approves or rejects an application.
    /// </summary>
    /// <param name="model">
    /// <see cref="ApplicationDecisionForm"/> containing a signed permission
    /// block and action type.
    /// </param>
    public async Task<IActionResult> SubmitApplication(
        [FromForm] ApplicationDecisionForm model
    )
    {
        // Validate and decrypt
        if (!ModelState.IsValid)
        {
            var notice =
                "Application action failed due to the following validation errors:";
            notice += ModelState.ToBulletList();

            return RedirectToAction("ViewApplication", Notice.Error(notice));
        }

        var decrypted = cryptoPermissions.DecryptPermissionBlock(
            model.PermissionBlock
        );
        var permissionBlock =
            JsonConvert.DeserializeObject<CreateAccountPermissionBlock>(
                decrypted
            );

        if (permissionBlock == null || !permissionBlock.IsValid())
        {
            return RedirectToAction(
                "ViewApplication",
                Notice.Error("Invalid permission block.")
            );
        }

        var uniqueId = permissionBlock.Application.UniqueId;

        // Complete action
        switch (model.Action)
        {
            case "Approve":
                try
                {
                    await AcceptApplication(permissionBlock.Application);
                }
                catch (Exception e)
                {
                    return RedirectToAction(
                        "ViewApplication",
                        Notice.Error($"User creation failed: {e.Message}")
                    );
                }

                applicationStore.DeleteApplication(uniqueId);

                return RedirectToAction(
                    "ViewApplication",
                    Notice.Info($"Application approved: {uniqueId}")
                );
            case "Reject":
                applicationStore.DeleteApplication(uniqueId);
                return RedirectToAction(
                    "ViewApplication",
                    Notice.Info($"Application rejected: {uniqueId}")
                );
            default:
                return RedirectToAction(
                    "ViewApplication",
                    Notice.Error($"Invalid application action type.")
                );
        }
    }

#region EncodePermissionBlock

    /// <summary>
    /// Handles submission of the <see cref="CreateAccountPermissionBlock"/>.
    /// </summary>
    /// <param name="model">
    /// Form to validate and process.
    /// </param>
    /// <returns>
    /// Rendered <see cref="CreateAccountPermissionBlock"/>.
    /// </returns>
    public IActionResult EncodePermissionBlock_CreateAccount(

Views/Admin/ArbitraryLdapSearch.cshtml
@{
    ViewData["Title"] = "Admin Tools";
}

<h1>Arbitrary LDAP search</h1>

<div class="panel inline">
    @using (Html.BeginForm("SubmitArbitraryLdapSearch", "Admin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <table class="form-table">
            <tr>
                <td><label for="BindDN">Bind DN</label></td>
                <td>
                    <select name="BindDN" id="BindDN">
                        <option value="cn=admin,dc=hush,dc=rip">cn=admin,dc=hush,dc=rip</option>
                        <option value="cn=config,dc=hush,dc=rip">cn=config,dc=hush,dc=rip</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td><label for="Password">Password</label></td>
                <td><input type="password" name="Password" id="Password"></td>
            </tr>
            <tr>
                <td><label for="SearchBase">Search Base</label></td>
                <td><input type="text" name="SearchBase" id="SearchBase" placeholder="dc=hush,dc=rip"></td>
            </tr>
            <tr>
                <td><label for="Filter">Filter</label></td>
                <td><input type="text" name="Filter" id="Filter" placeholder="(objectClass=inetOrgPerson)"></td>
            </tr>
            <tr>
                <td><label for="Scope">Scope</label></td>
                <td>
                    <select name="Scope" id="Scope">
                        <option value="base">Base</option>
                        <option value="one">One</option>
                        <option value="sub">Sub</option>
                        <option value="children">Children</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Submit"></td>
            </tr>
        </table>
    }
</div>

Views/Admin/DecodePermissionBlock.cshtml
@{
    ViewData["Title"] = "Admin Tools";
}

<h1>Decode permission block</h1>

<div class="panel inline">
    @using (Html.BeginForm("SubmitDecodePermissionBlock", "Admin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <table class="form-table">
            <tr>
                <td><label for="message">Message</label></td>
                <td><textarea name="message" id="message" cols="60" rows="12"></textarea></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Submit" aria-label="submit"></td>
            </tr>
        </table>
    }
</div>

Views/Admin/DeleteAccount.cshtml
@{
    ViewData["Title"] = "Admin Tools";
}

<h1>Delete account</h1>

<div class="panel inline">
    @using (Html.BeginForm("SubmitDeleteAccount", "Admin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <table class="form-table">
            <tr>
                <td><label for="PermissionBlock">Permission Block</label></td>
                <td><textarea type="text" name="PermissionBlock" id="PermissionBlock" cols="60" rows="12"></textarea></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Submit" aria-label="Submit"></td>
            </tr>
        </table>
    }
</div>

Views/Admin/Index.cshtml
@using HushWeb.Services.CryptoPermissions;

@{
    ViewData["Title"] = "Admin Tools";

    string EncodePermissionBlockLink(string permissionType) =>
        $"Admin/EncodePermissionBlock/{permissionType}";
}

<h1>Admin Tools</h1>

<ul>
    <li><a asp-action="ViewApplication">View Applications</a></li>
    <li><a asp-action="DeleteAccount">Delete account</a></li>
    <li><a asp-action="ArbitraryLdapSearch">Arbitrary LDAP search</a></li>
    <li><a asp-action="DecodePermissionBlock">Decode permission block</a></li>
    <li>
        Encode permission block
        <ul>
            @foreach (var permissionType in PermissionType.AllTypes)
            {
                <li><a href="@EncodePermissionBlockLink(permissionType)">@permissionType</a></li>
            }
        </ul>
    </li>
</ul>

Views/Admin/ViewApplication.cshtml
@{
    ViewData["Title"] = "Admin Tools";
}

<partial name="_Notice" />

<h1>View applications</h1>

<section>
    <h2 class="section-title">Application selector</h2>

    <div class="panel inline">
        @using (Html.BeginForm("ViewApplication", "Admin", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <table class="form-table">
                <tr>
                    <td><label for="UniqueId">Unique Id</label></td>
                    <td>
                        <select name="UniqueId" id="UniqueId">
                            @if (ViewBag.uniqueId != null)
                            {
                                <option value="@ViewBag.uniqueId">@ViewBag.uniqueId</option>
                            }

                            @foreach (var applicantUniqueId in ViewBag.applicantUniqueIds)
                            {
                                @if (ViewBag.uniqueId == null || applicantUniqueId != ViewBag.uniqueId)
                                {
                                    <option value="@applicantUniqueId">@applicantUniqueId</option>
                                }
                            }
                        </select>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="View" aria-label="View">
                    </td>
                </tr>
            </table>
        }
    </div>
</section>

@if (ViewBag.uniqueId != null)
{
    <section>
        <h2 class="section-title">
            Selected application: 
            <span class="applicant">@ViewBag.uniqueId</span>
        </h2>

        <div class="panel">
            @using (Html.BeginForm("SubmitApplication", "Admin", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <table class="form-table">
                    <tr>
                        <td><label>Application</label></td>
                        <td>
                            <textarea cols="60" rows="19">@ViewBag.permissionBlock</textarea>
                            <p class="sublabel">
                                Application is read-only.
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="PermissionBlock">Signed message</label></td>
                        <td>
                            <textarea
                                name="PermissionBlock"
                                id="PermissionBlock"
                                cols="60"
                                rows="12"></textarea>
                            <p class="sublabel">
                                The signed message must be unarmored.
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <input class="reject" type="submit" name="Action" value="Reject" aria-label="Reject">
                            <input class="approve" type="submit" name="Action" value="Approve" aria-label="Approve">
                        </td>
                    </tr>
                </table>
            }
        </div>
    </section>
}